import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from '@clerk/themes'
import {Toaster} from "sonner";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ClerkProvider appearance={{
          baseTheme: dark,
      }}>
          <html lang="en">
          <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
                  <SidebarTrigger />
                  <Suspense>
                      {children}
                  </Suspense>
                  <Toaster richColors position="bottom-right" />
              </main>
          </SidebarProvider>
          </body>
          </html>
      </ClerkProvider>

  );
}
